M48
; DRILL file {KiCad 7.0.6-0} date 2023 August 12, Saturday 13:32:15
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-12T13:32:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.0888Y-3.456
T2
X3.95Y-3.02
X3.99Y-3.22
X4.03Y-3.02
T3
X4.0Y-2.84
X4.0Y-4.105
X6.2598Y-2.84
X6.2598Y-4.105
T1
G00X4.0888Y-3.6767
M15
G01X4.0888Y-3.6905
M16
G05
T0
M30
